"""
TCRW Fig 3 — dump exact-Python observables to gnuplot-friendly .txt files.
============================================================================

For every Fig 3 panel, write a `tcrw_fig3X_exact.txt` file with the SAME
column layout as the matching `tcrw_fig3X_summary.txt` produced by the
Fortran driver.  This way the existing `.gnu` files can plot Fortran MC
(markers) and exact Python (lines) on the same axes by adding a single
extra `plot` clause — no Python plotting needed.

Usage
-----
    python3 tcrw_fig3_exact_dump.py        # writes all _exact.txt files
    bash run.sh tcrw-plot-fig3a            # gnuplot picks them up automatically

File map (mirrors Fortran summaries column-for-column)
------------------------------------------------------
    tcrw_fig3a_exact.txt        L  D_r  ratio  P_edge  P_bulk  n_edge  n_bulk
    tcrw_fig3b_exact.txt        L  D_r  ratio  |J_Dr|  |J_om|  Jx_Dr Jy_Dr Jx_om Jy_om
    tcrw_fig3cde_exact.txt      iD D_r  y  Jx_Dr Jy_Dr Jx_om Jy_om |J_Dr| th_Dr |J_om| th_om
    tcrw_fig3e_exact.txt        iD D_r  Jx_Dr_tot Jy_Dr_tot Jx_om_tot Jy_om_tot th_Dr_tot th_om_tot
    tcrw_fig3f_exact.txt        L  ω    ratio  P_edge  P_bulk  n_edge  n_bulk
    tcrw_fig3g_exact.txt        L  ω    ratio  |J_Dr|  |J_om|  Jx_Dr Jy_Dr Jx_om Jy_om
    tcrw_fig3hij_exact.txt      iW ω    y  Jx_Dr Jy_Dr Jx_om Jy_om |J_Dr| th_Dr |J_om| th_om
    tcrw_fig3j_exact.txt        iW ω    Jx_Dr_tot Jy_Dr_tot Jx_om_tot Jy_om_tot th_Dr_tot th_om_tot

Per-step normalisation
----------------------
The Fortran J columns are integer COUNTS (sum over T_meas MC steps).
The exact Python J's are dimensionless probabilities-per-step.  To overlay
on the same axes you have two options:
  (a) divide the Fortran count by T_use → both quantities per-step
  (b) multiply the exact value by T_use → both quantities counts

Option (a) is what the existing `_crosscheck.py` scripts do.  For the
gnuplot overlay we recommend the same: pre-divide Fortran by T_use in the
`.gnu` file using the column expression `($4/T)`.  The exact .txt is
already per-step so it plots straight through.

Author: Prashant Bisht, TIFR Hyderabad
"""
from __future__ import annotations
import os
import numpy as np
import tcrw_fig3_exact as ex


HERE = os.path.dirname(os.path.abspath(__file__))


# Parameter grids — must match the Fortran summaries
N_Dr        = 25
D_r_grid    = np.logspace(-4.0, 0.0, N_Dr)
N_omega     = 21
omega_grid  = np.linspace(0.0, 1.0, N_omega)
L_LIST_a    = (4, 9, 19, 49)
L_LIST_f    = (10, 19, 49)
L_HEATMAP   = 10
D_r_FIXED   = 1e-3


def _fmt_header(title: str, columns: str) -> str:
    """Standard gnuplot-friendly header (lines starting with `#`)."""
    return (f"# {title}\n"
            f"# Generated by tcrw_fig3_exact_dump.py — exact authors-Python data\n"
            f"# columns: {columns}\n")


# ---------------------------------------------------------------------------
def dump_fig3a():
    """Mirror tcrw_fig3a_summary.txt: L  D_r  ratio  P_edge  P_bulk  n_edge  n_bulk"""
    out = os.path.join(HERE, "tcrw_fig3a_exact.txt")
    with open(out, "w") as f:
        f.write(_fmt_header(
            "TCRW Fig 3(a) exact: P_edge/P_bulk vs D_r (ω=1, OBC)",
            "L   D_r   ratio   P_edge_norm   P_bulk_norm   n_edge   n_bulk"))
        for L in L_LIST_a:
            for D in D_r_grid:
                pi, *_ = ex.steady_state_and_currents(1.0, float(D), L)
                P_e, P_b, n_e, n_b = ex.edge_bulk_per_site(pi, L)
                ratio = P_e / P_b if P_b > 0 else float("nan")
                f.write(f"{L:>3}  {D:>13.5e}  {ratio:>13.5e}  "
                        f"{P_e:>13.5e}  {P_b:>13.5e}  "
                        f"{n_e:>8d}  {n_b:>10d}\n")
            f.write("\n")   # blank line between L blocks → gnuplot 'index'
    print(f"  wrote {out}")


def dump_fig3b():
    """Mirror tcrw_fig3b_summary.txt: L  D_r  ratio  |J_Dr|  |J_om|  Jx_Dr Jy_Dr Jx_om Jy_om"""
    out = os.path.join(HERE, "tcrw_fig3b_exact.txt")
    with open(out, "w") as f:
        f.write(_fmt_header(
            "TCRW Fig 3(b) exact: |J_Dr|/|J_om| at left wall vs D_r (ω=1, OBC)",
            "L   D_r   ratio   |J_Dr|_wall   |J_om|_wall   "
            "Jx_w_Dr  Jy_w_Dr  Jx_w_om  Jy_w_om"))
        for L in L_LIST_a:
            for D in D_r_grid:
                _, JD, JO, _ = ex.steady_state_and_currents(1.0, float(D), L)
                t = ex.left_wall_J_totals(JD, JO, L)
                f.write(f"{L:>3}  {D:>13.5e}  {t['ratio']:>13.5e}  "
                        f"{t['abs_Dr']:>13.5e}  {t['abs_om']:>13.5e}  "
                        f"{t['Jx_Dr_tot']:>+13.5e}  {t['Jy_Dr_tot']:>+13.5e}  "
                        f"{t['Jx_om_tot']:>+13.5e}  {t['Jy_om_tot']:>+13.5e}\n")
            f.write("\n")
    print(f"  wrote {out}")


def dump_fig3cde():
    """Per-y left-wall current vs D_r (and totals for 3(e))."""
    out_per = os.path.join(HERE, "tcrw_fig3cde_exact.txt")
    out_tot = os.path.join(HERE, "tcrw_fig3e_exact.txt")
    with open(out_per, "w") as fp, open(out_tot, "w") as ft:
        fp.write(_fmt_header(
            "TCRW Fig 3(c)/(d) exact: per-y left-wall current vs D_r (L=10, ω=1)",
            "iD  D_r  y  Jx_Dr Jy_Dr Jx_om Jy_om |J_Dr| th_Dr |J_om| th_om"))
        ft.write(_fmt_header(
            "TCRW Fig 3(e) exact: total wall angles vs D_r (L=10, ω=1)",
            "iD  D_r  Jx_Dr_tot Jy_Dr_tot Jx_om_tot Jy_om_tot th_Dr_tot th_om_tot"))
        for iD, D in enumerate(D_r_grid, start=1):
            _, JD, JO, _ = ex.steady_state_and_currents(1.0, float(D), L_HEATMAP)
            per = ex.left_wall_J_per_y(JD, JO, L_HEATMAP)
            tot = ex.left_wall_J_totals(JD, JO, L_HEATMAP)
            for y in range(L_HEATMAP + 1):
                fp.write(f"{iD:>3}  {D:>13.5e}  {y:>3}  "
                         f"{per['Jx_Dr'][y]:>+13.5e}  {per['Jy_Dr'][y]:>+13.5e}  "
                         f"{per['Jx_om'][y]:>+13.5e}  {per['Jy_om'][y]:>+13.5e}  "
                         f"{per['absJ_Dr'][y]:>13.5e}  {per['th_Dr'][y]:>+9.5f}  "
                         f"{per['absJ_om'][y]:>13.5e}  {per['th_om'][y]:>+9.5f}\n")
            fp.write("\n")
            ft.write(f"{iD:>3}  {D:>13.5e}  "
                     f"{tot['Jx_Dr_tot']:>+13.5e}  {tot['Jy_Dr_tot']:>+13.5e}  "
                     f"{tot['Jx_om_tot']:>+13.5e}  {tot['Jy_om_tot']:>+13.5e}  "
                     f"{tot['th_Dr_tot']:>+9.5f}  {tot['th_om_tot']:>+9.5f}\n")
    print(f"  wrote {out_per}")
    print(f"  wrote {out_tot}")


def dump_fig3f():
    out = os.path.join(HERE, "tcrw_fig3f_exact.txt")
    with open(out, "w") as f:
        f.write(_fmt_header(
            "TCRW Fig 3(f) exact: P_edge/P_bulk vs ω (D_r=1e-3, OBC)",
            "L   ω   ratio   P_edge_norm   P_bulk_norm   n_edge   n_bulk"))
        for L in L_LIST_f:
            for w in omega_grid:
                pi, *_ = ex.steady_state_and_currents(float(w), D_r_FIXED, L)
                P_e, P_b, n_e, n_b = ex.edge_bulk_per_site(pi, L)
                ratio = P_e / P_b if P_b > 0 else float("nan")
                f.write(f"{L:>3}  {w:>7.4f}  {ratio:>13.5e}  "
                        f"{P_e:>13.5e}  {P_b:>13.5e}  "
                        f"{n_e:>8d}  {n_b:>10d}\n")
            f.write("\n")
    print(f"  wrote {out}")


def dump_fig3g():
    out = os.path.join(HERE, "tcrw_fig3g_exact.txt")
    with open(out, "w") as f:
        f.write(_fmt_header(
            "TCRW Fig 3(g) exact: |J_Dr|/|J_om| at left wall vs ω (D_r=1e-3, OBC)",
            "L   ω   ratio   |J_Dr|_wall   |J_om|_wall   "
            "Jx_w_Dr  Jy_w_Dr  Jx_w_om  Jy_w_om"))
        for L in L_LIST_f:
            for w in omega_grid:
                _, JD, JO, _ = ex.steady_state_and_currents(float(w), D_r_FIXED, L)
                t = ex.left_wall_J_totals(JD, JO, L)
                f.write(f"{L:>3}  {w:>7.4f}  {t['ratio']:>13.5e}  "
                        f"{t['abs_Dr']:>13.5e}  {t['abs_om']:>13.5e}  "
                        f"{t['Jx_Dr_tot']:>+13.5e}  {t['Jy_Dr_tot']:>+13.5e}  "
                        f"{t['Jx_om_tot']:>+13.5e}  {t['Jy_om_tot']:>+13.5e}\n")
            f.write("\n")
    print(f"  wrote {out}")


def dump_fig3hij():
    out_per = os.path.join(HERE, "tcrw_fig3hij_exact.txt")
    out_tot = os.path.join(HERE, "tcrw_fig3j_exact.txt")
    with open(out_per, "w") as fp, open(out_tot, "w") as ft:
        fp.write(_fmt_header(
            "TCRW Fig 3(h)/(i) exact: per-y left-wall current vs ω (L=10, D_r=1e-3)",
            "iW  ω  y  Jx_Dr Jy_Dr Jx_om Jy_om |J_Dr| th_Dr |J_om| th_om"))
        ft.write(_fmt_header(
            "TCRW Fig 3(j) exact: total wall angles vs ω (L=10, D_r=1e-3)",
            "iW  ω  Jx_Dr_tot Jy_Dr_tot Jx_om_tot Jy_om_tot th_Dr_tot th_om_tot"))
        for iW, w in enumerate(omega_grid, start=1):
            _, JD, JO, _ = ex.steady_state_and_currents(float(w), D_r_FIXED, L_HEATMAP)
            per = ex.left_wall_J_per_y(JD, JO, L_HEATMAP)
            tot = ex.left_wall_J_totals(JD, JO, L_HEATMAP)
            for y in range(L_HEATMAP + 1):
                fp.write(f"{iW:>3}  {w:>7.4f}  {y:>3}  "
                         f"{per['Jx_Dr'][y]:>+13.5e}  {per['Jy_Dr'][y]:>+13.5e}  "
                         f"{per['Jx_om'][y]:>+13.5e}  {per['Jy_om'][y]:>+13.5e}  "
                         f"{per['absJ_Dr'][y]:>13.5e}  {per['th_Dr'][y]:>+9.5f}  "
                         f"{per['absJ_om'][y]:>13.5e}  {per['th_om'][y]:>+9.5f}\n")
            fp.write("\n")
            ft.write(f"{iW:>3}  {w:>7.4f}  "
                     f"{tot['Jx_Dr_tot']:>+13.5e}  {tot['Jy_Dr_tot']:>+13.5e}  "
                     f"{tot['Jx_om_tot']:>+13.5e}  {tot['Jy_om_tot']:>+13.5e}  "
                     f"{tot['th_Dr_tot']:>+9.5f}  {tot['th_om_tot']:>+9.5f}\n")
    print(f"  wrote {out_per}")
    print(f"  wrote {out_tot}")


# ---------------------------------------------------------------------------
if __name__ == "__main__":
    print("Dumping exact authors-Python data for Fig 3 panels (gnuplot-ready):")
    dump_fig3a()
    dump_fig3b()
    dump_fig3cde()
    dump_fig3f()
    dump_fig3g()
    dump_fig3hij()
    print("\nDone.  Files match Fortran column layout — point .gnu files at them.")
